=== jbailencanellas/Exercisis_ll_mm/3a evaluació/ejercicios/comandes.dtd
<!ELEMENT comandes (comanda*)>
<!ELEMENT comanda (num_serie, quantitat, pes?)>
<!ELEMENT num_serie (#PCDATA)>
<!ELEMENT quantitat (#PCDATA)>
<!ELEMENT pes (#PCDATA)>

=== jbailencanellas/Exercisis_ll_mm/3a evaluació/ejercicios/e04.02-02.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE comandes SYSTEM "comandes.dtd">
<comandes>
    <comanda>
        <num_serie>4534532</num_serie>
        <quantitat>3</quantitat>
        <pes>50kg</pes>
    </comanda>
    <comanda>
        <num_serie>3242342</num_serie>
        <quantitat>2</quantitat>
    </comanda>
</comandes>
