=== jbailencanellas/Exercisis_ll_mm/3a_evaluació/ejercicios/productes.dtd
<!ELEMENT productes (ratolí, teclat, monitor)+>
<!ELEMENT ratolí (codi, nom?, descripció?)>
<!ELEMENT teclat (codi, nom?, descripció?)>
<!ELEMENT monitor (codi, nom?, descripció?)>
<!ELEMENT codi (#PCDATA)>
<!ELEMENT nom (#PCDATA)>
<!ELEMENT descripció (#PCDATA)>

=== jbailencanellas/Exercisis_ll_mm/3a evaluació/ejercicios/e04.02-03.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE productes SYSTEM "productes.dtd">
<productes>
    <ratolí>
        <codi>7553159</codi>
        <nom>Razer Viper</nom>
        <descripció>Ratón ligero</descripció>
    </ratolí>
    <teclat>
        <codi>852456</codi>
        <descripció>Un ratón</descripció>
    </teclat>
    <monitor>
        <codi>123654</codi>
        <nom>Corsair Strafe</nom>
    </monitor>
</productes>
