=== jbailencanellas/Exercisis_ll_mm/3a_evaluació/ejercicios/recetas.dtd
<!ELEMENT receta (name, ingrediente*)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT ingrediente (nombre, uso?, cantidad?)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT uso (#PCDATA)>
<!ELEMENT cantidad (#PCDATA)>

=== jbailencanellas/Exercisis_ll_mm/3a evaluació/ejercicios/e04.02-04.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE receta SYSTEM "recetas.dtd">
<receta>
    <name>Quiche de verduras</name>
    <ingrediente>
        <nombre>Harina de trigo</nombre>
        <uso>Para la masa quebrada</uso>
        <cantidad>200 g</cantidad>
    </ingrediente>
    <ingrediente>
        <nombre>Mantequilla</nombre>
        <uso>Para la masa quebrada</uso>
        <cantidad>100 g</cantidad>
    </ingrediente>
    <ingrediente>
        <nombre>Clara de huevo</nombre>
        <uso>Para la masa quebrada</uso>
        <cantidad>60-70 g</cantidad>
    </ingrediente>
    <ingrediente>
        <nombre>Cebolleta</nombre>
        <uso>Para el relleno</uso>
        <cantidad>2</cantidad>
    </ingrediente>
    <ingrediente>
        <nombre>Zanahoria</nombre>
        <uso>Para el relleno</uso>
        <cantidad>1</cantidad>
    </ingrediente>
    <ingrediente>
        <nombre>Calabacín</nombre>
        <uso>para el relleno</uso>
        <cantidad>0.5</cantidad>
    </ingrediente>
    <ingrediente>
        <nombre>Queso rallado</nombre>
        <uso>para el relleno</uso>
        <cantidad>100 g</cantidad>
    </ingrediente>
    <ingrediente>
        <nombre>Huevo</nombre>
        <uso>Para el relleno</uso>
        <cantidad>3</cantidad>
    </ingrediente>
    <ingrediente>
        <nombre>Nata líquida</nombre>
        <uso>Para el relleno</uso>
        <cantidad>150 ml</cantidad>
    </ingrediente>
    <ingrediente>
        <nombre>Aceite de oliva virgen extra</nombre>
    </ingrediente>
    <ingrediente>
        <nombre>Sal</nombre>
    </ingrediente>
    <ingrediente>
        <nombre>Pimienta molida</nombre>
    </ingrediente>

</receta>
