=== jbailencanellas/Exercisis_ll_mm/3a_evaluació/ejercicios/vendes.dtd
<!ELEMENT vendes (venda+)>
<!ELEMENT venda (vendacredit?, vendainmediata?)>
<!ELEMENT vendacredit ( datapagament, quantitat )>
<!ELEMENT datapagament (#PCDATA)>
<!ELEMENT quantitat (#PCDATA)>
<!ELEMENT vendainmediata ( quantity, divisa )>
<!ELEMENT quantity (#PCDATA)>
<!ELEMENT divisa (#PCDATA)>

=== jbailencanellas/Exercisis_ll_mm/3a evaluació/ejercicios/E04.02-05.XML
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE vendes SYSTEM "vendes.dtd">
<vendes>
    <venda>
        <vendacredit>
            <datapagament>10/04/2024</datapagament>
            <quantitat>5</quantitat>
        </vendacredit>
        <vendainmediata>
            <quantity>3</quantity>
            <divisa>â‚¬</divisa>
        </vendainmediata>
    </venda>
    <venda>
    </venda>
    <venda>
        <vendacredit>
            <datapagament>19/12/2023</datapagament>
            <quantitat>10</quantitat>
        </vendacredit>
    </venda>
    <venda>
        <vendainmediata>
            <quantity>45</quantity>
            <divisa>$</divisa>
        </vendainmediata>
    </venda>
</vendes>
